/**
 * @license Apache-2.0
 * Thinking spinner phrases for TitanX chat.
 * Regular mode: funny tech/geek phrases (inspired by Daniel Miessler's Claude Code list)
 * Bollywood mode: iconic Hindi meme dialogues as easter egg
 */

/** Funny thinking verbs shown while agents are processing */
export const THINKING_PHRASES = [
  'Krahing',
  'Hill-climbing',
  'Caffeinating',
  'Sandworming',
  'Battle-rooming',
  'Dragon-army-commanding',
  'Enemy-gate-downing',
  'Jacking in',
  'Flatlining',
  'ICE-breaking',
  'Console-cowboying',
  'Neuromancing',
  'Three-body-probleming',
  'Foundation-building',
  'Psychohistorying',
  'Stormlight-archiving',
  'Murderbot-diarying',
  'Ready-player-oneing',
  'Warp-driving',
  'Making it so',
  'Engaging',
  'Boldly going',
  'Mind-melding',
  'Logically-proceeding',
  'Interstellaring',
  'Bullet-timing',
  'Red-pilling',
  'Matrixing',
  'Obstacle-is-the-waying',
  'Cogito-ergo-summing',
  'Cave-allegory-escaping',
  'Eudaimonia-chasing',
  'Amor-fati-ing',
  'Spiraling-out',
  'Lateralizing',
  'Djent-chugging',
  'Kaizen-improving',
  'Wabi-sabi-accepting',
  'Kintsugi-repairing',
  'Zazen-meditating',
  'Koan-contemplating',
  'Pour-overing',
  'Dialing-in-the-grind',
  'Extracting',
  'Tamping',
  'Cupping',
  'Hooah-ing',
  'Rucking',
  'Roger-that-ing',
  'Typesetting',
  'Kerning',
  'Pentesting',
  'Fuzzing',
  'Zero-daying',
  'Buffer-overflowing',
  'Privilege-escalating',
  'Shellcode-injecting',
  'MITRE-ATTACKing',
  'Kill-chain-mapping',
  'Bug-bountying',
  'CVE-triaging',
  'Fabric-patterning',
  'Wisdom-extracting',
  'Swarm-deploying',
  'Gradient-descending',
  'Backpropagating',
  'Transformer-encoding',
  'Self-attending',
  'Temperature-sampling',
  'Chain-of-thought-reasoning',
  'Dragon-slaying',
  'Nat-twentying',
  'Side-questing',
  'Speed-running',
  'Git-pushing',
  'Docker-containerizing',
  'Yak-shaving',
  'Bikeshedding',
  'Chmod-777ing',
  'Consciousness-pondering',
  'Turing-testing',
  'Ship-of-Theseusing',
  'Sonder-feeling',
  'Sisyphus-imagining-happy',
  'Stranging in a strange land',
  'Naming the wind',
  'Spice-flowing',
  'Picard-maneuvering',
  'Fascinating-ing',
  'Turkish-negotiating',
  'Royale-with-cheesing',
  'Seneca-lettering',
  'Samurai-coding',
  'Seppuku-refactoring',
];

/** Iconic Bollywood meme dialogues — shown when Bollywood mode is enabled */
export const BOLLYWOOD_DIALOGUES = [
  'Mogambo khush hua! 🎬',
  'Kitne aadmi the? 🤔',
  'Bhaisahab, aap convince ho gaye ya main aur bolun?',
  'Jor jor se bolke sabko scheme bata de! 📢',
  'Seh lenge thoda 😤',
  'Abhi maza aaega na bhidu! 🎉',
  'Sala yeh dukh kahe khatam nahi hote be 😢',
  '50 rupees kaat overacting ka ✂️',
  'Main expert hoon, merko sab aata hai 🧠',
  'Bhaisaab ye kis line mein aa gaye aap 🚶',
  'Mujhe ghar jana hai 🏠',
  'Jal lijiye 🥤',
  'Tension lene ka nahi, sirf dene ka 😎',
  "How's the josh? HIGH SAAAAR! 🫡",
  'Dosti mein no sorry, no thank you 🤝',
  'Pushpa, I hate tears 😭',
  'Kutte, kaminey, main tera khoon pee jaunga! 🧛',
  'Babumoshai, zindagi badi honi chahiye... lambi nahi 🎭',
  'Rishte mein toh hum tumhare baap lagte hain 👨‍👦',
  'Picture abhi baaki hai mere dost 🎬',
  'Don ko pakadna mushkil hi nahi, namumkin hai 🏃',
  'Yeh Baburao ka style hai 😎',
  'Utha le re baba, utha le 🙏',
  'Ae dada, chill maar 🧊',
  'Hera Pheri chal rahi hai yahan 🎪',
  'Kuch toh gadbad hai Daya 🔍',
  'Crime Master Gogo naam hai mera 🦹',
  'Thappad se darr nahi lagta sahab 💪',
  'All izz well 🙆',
];

/** Get a random thinking phrase based on mode */
export function getThinkingPhrase(bollywoodMode: boolean): string {
  const list = bollywoodMode ? BOLLYWOOD_DIALOGUES : THINKING_PHRASES;
  return list[Math.floor(Math.random() * list.length)];
}
